// src/app/layout.tsx (수정 후)

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// 1. 우리가 만든 Header 컴포넌트를 가져옵니다.
import Header from "@/components/Header"; 

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* 2. body 태그 바로 아래, 모든 페이지 내용({children}) 위에 Header를 놓습니다. */}
        <Header />
        
        {/* 이 {children} 자리에 page.tsx 내용이 렌더링 됩니다. */}
        {children}
        
        {/* 푸터도 마찬가지로 여기에 추가하면 모든 페이지 하단에 보이게 됩니다. */}
        {/* <Footer /> */}
      </body>
    </html>
  );
}